In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
import zipfile

In [3]:
%time
print('Extracting ZIP.')
z = zipfile.ZipFile('P:\\Python Projects\\AI_curces\\O_Reily\\datasets\\all_mtg_cards.csv.zip', 'r')

CPU times: total: 0 ns
Wall time: 0 ns
Extracting ZIP.

In [4]:
z.extractall(path='P:\\Python Projects\\AI_curces\\O_Reily\\datasets\\data')

In [5]:
df = pd.read_csv('.//datasets//data//all_mtg_cards.csv')

C:\Users\Сергей\AppData\Local\Temp\ipykernel_20924\3173835817.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('.//datasets//data//all_mtg_cards.csv')

In [6]:
df.head(5)

,name,multiverse_id,layout,names,mana_cost,cmc,colors,color_identity,type,supertypes,...,foreign_names,printings,original_text,original_type,legalities,source,image_url,set,set_name,id
0,Ancestor's Chosen,130550.0,normal,NaN,{5}{W}{W},7.0,['White'],['W'],Creature — Human Cleric,NaN,...,"[{'name': 'Ausgewählter der Ahnfrau', 'text': ...","['10E', 'JUD', 'UMA']",First strike (This creature deals combat damag...,Creature - Human Cleric,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,http://gatherer.wizards.com/Handlers/Image.ash...,10E,Tenth Edition,5f8287b1-5bb6-5f4c-ad17-316a40d5bb0c
1,Ancestor's Chosen,NaN,normal,NaN,{5}{W}{W},7.0,['White'],['W'],Creature — Human Cleric,NaN,...,NaN,"['10E', 'JUD', 'UMA']",NaN,NaN,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,NaN,10E,Tenth Edition,b7c19924-b4bf-56fc-aa73-f586e940bd42
2,Angel of Mercy,129465.0,normal,NaN,{4}{W},5.0,['White'],['W'],Creature — Angel,NaN,...,"[{'name': 'Engel der Gnade', 'text': 'Fliegend...","['10E', '8ED', '9ED', 'DDC', 'DVD', 'IMA', 'IN...",Flying (This creature can't be blocked except ...,Creature - Angel,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,http://gatherer.wizards.com/Handlers/Image.ash...,10E,Tenth Edition,57aaebc1-850c-503d-9f6e-bb8d00d8bf7c
3,Angel of Mercy,NaN,normal,NaN,{4}{W},5.0,['White'],['W'],Creature — Angel,NaN,...,NaN,"['10E', '8ED', '9ED', 'DDC', 'DVD', 'IMA', 'IN...",NaN,NaN,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,NaN,10E,Tenth Edition,8fd4e2eb-3eb4-50ea-856b-ef638fa47f8a
4,Angelic Blessing,129711.0,normal,NaN,{2}{W},3.0,['White'],['W'],Sorcery,NaN,...,"[{'name': 'Himmlischer Segen', 'text': 'Eine K...","['10E', '9ED', 'EXO', 'P02', 'POR', 'PS11', 'S...",Target creature gets +3/+3 and gains flying un...,Sorcery,"[{'format': 'Commander', 'legality': 'Legal'},...",NaN,http://gatherer.wizards.com/Handlers/Image.ash...,10E,Tenth Edition,55bd38ca-dc73-5c06-8f80-a6ddd2f44382

In [7]:
df.tail(5)

,name,multiverse_id,layout,names,mana_cost,cmc,colors,color_identity,type,supertypes,...,foreign_names,printings,original_text,original_type,legalities,source,image_url,set,set_name,id
66765,Into the Roil,NaN,normal,NaN,{1}{U},2.0,['Blue'],['U'],Instant,NaN,...,NaN,"['C14', 'C17', 'C18', 'CMR', 'DDM', 'PS11', 'Z...",NaN,NaN,"[{'format': 'Alchemy', 'legality': 'Legal'}, {...",NaN,NaN,ZNR,Zendikar Rising,3f492516-7767-5ed7-a1d4-e3f7c06aee2f
66766,Bloodchief's Thirst,NaN,normal,NaN,{B},1.0,['Black'],['B'],Sorcery,NaN,...,NaN,['ZNR'],NaN,NaN,"[{'format': 'Alchemy', 'legality': 'Legal'}, {...",NaN,NaN,ZNR,Zendikar Rising,3f9a0369-5fe7-5aee-85fe-3cfaacd275af
66767,Roil Eruption,NaN,normal,NaN,{1}{R},2.0,['Red'],['R'],Sorcery,NaN,...,NaN,['ZNR'],NaN,NaN,"[{'format': 'Alchemy', 'legality': 'Legal'}, {...",NaN,NaN,ZNR,Zendikar Rising,97577e9e-69a9-5a8b-9c24-a72703790046
66768,Roiling Regrowth,NaN,normal,NaN,{2}{G},3.0,['Green'],['G'],Instant,NaN,...,NaN,['ZNR'],NaN,NaN,"[{'format': 'Alchemy', 'legality': 'Legal'}, {...",NaN,NaN,ZNR,Zendikar Rising,deb51cbd-b890-5b2d-9d6f-7b896e16c6fd
66769,Kargan Warleader,NaN,normal,NaN,{1}{R}{W},3.0,"['Red', 'White']","['R', 'W']",Creature — Human Warrior,NaN,...,NaN,['ZNR'],NaN,NaN,"[{'format': 'Brawl', 'legality': 'Legal'}, {'f...",NaN,NaN,ZNR,Zendikar Rising,46407d93-df48-5161-95fe-f24086746663

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66770 entries, 0 to 66769
Data columns (total 39 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            66770 non-null  object
 1   multiverse_id   47455 non-null  float64
 2   layout          66770 non-null  object
 3   names           0 non-null      float64
 4   mana_cost       58100 non-null  object
 5   cmc             66770 non-null  float64
 6   colors          52612 non-null  object
 7   color_identity  59739 non-null  object
 8   type            66770 non-null  object
 9   supertypes      9912 non-null   object
 10  subtypes        40903 non-null  object
 11  rarity          66770 non-null  object
 12  text            65805 non-null  object
 13  flavor          34412 non-null  object
 14  artist          66759 non-null  object
 15  number          66770 non-null  object
 16  power           31332 non-null  object
 17  toughness       31332 non-null  object
 18  loyalty         1075 non-null   object
 19  variations      12590 non-null  object
 20  watermark       5110 non-null   object
 21  border          0 non-null      float64
 22  timeshifted     0 non-null      float64
 23  hand            119 non-null    float64
 24  life            119 non-null    float64
 25  reserved        0 non-null      float64
 26  release_date    0 non-null      float64
 27  starter         0 non-null      float64
 28  rulings         37243 non-null  object
 29  foreign_names   41285 non-null  object
 30  printings       66770 non-null  object
 31  original_text   46485 non-null  object
 32  original_type   47435 non-null  object
 33  legalities      65380 non-null  object
 34  source          0 non-null      float64
 35  image_url       47455 non-null  object
 36  set             66770 non-null  object
 37  set_name        66770 non-null  object
 38  id              66770 non-null  object
dtypes: float64(11), object(28)
memory usage: 19.9+ MB

In [50]:
data = df.copy(d)

In [51]:
data = data.drop_duplicates()

In [58]:
data_task_1 = data[['colors', 'rarity']].dropna()

In [59]:
data_task_1

                 colors    rarity
0             ['White']  Uncommon
1             ['White']  Uncommon
2             ['White']  Uncommon
3             ['White']  Uncommon
4             ['White']    Common
...                 ...       ...
66765          ['Blue']    Common
66766         ['Black']  Uncommon
66767           ['Red']    Common
66768         ['Green']  Uncommon
66769  ['Red', 'White']  Uncommon

[52612 rows x 2 columns]

In [61]:
data_task_1['colors'].unique()

array(["['White']", "['Blue']", "['Black']", "['Red']", "['Green']",
       "['Green', 'Blue']", "['Black', 'Green', 'Blue', 'White']",
       "['Black', 'Blue']", "['Black', 'Red', 'Blue', 'White']",
       "['Red', 'Blue']", "['Black', 'Green']", "['Black', 'Red']",
       "['Blue', 'White']", "['Green', 'Red']", "['Black', 'White']",
       "['Black', 'Red', 'White']", "['Black', 'Green', 'Red']",
       "['Black', 'Green', 'Red', 'Blue', 'White']", "['Green', 'White']",
       "['Green', 'Red', 'Blue']", "['Black', 'Blue', 'White']",
       "['Red', 'White']", "['Black', 'Red', 'Blue']",
       "['Green', 'Blue', 'White']", "['Green', 'Red', 'White']",
       "['Black', 'Green', 'Blue']", "['Red', 'Blue', 'White']",
       "['Black', 'Green', 'White']", "['Green', 'Red', 'Blue', 'White']",
       "['Black', 'Green', 'Red', 'White']",
       "['Black', 'Green', 'Red', 'Blue']", "['White', 'Blue']",
       "['Blue', 'Black']", "['Blue', 'Green']", "['White', 'Red']",
       "['Blue', 'Red']", "['Red', 'Green']", "['White', 'Green']",
       "['White', 'Black']"], dtype=object)

In [62]:
data_task_1["num_colors"] = data_task_1[i for i in data_task_1["colors"].unique()]

SyntaxError: invalid syntax (2700538745.py, line 1)

In [64]:
colors_unique = data_task_1['colors'].unique()
colors_unique_i = []

In [68]:
for colors in colors_unique:
    colors_unique_i.append(colors_unique.index)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

Для цветов будем использовать колонку colors

Для редкости будем использовать колонку rarity

# task_1

In [11]:
sns.barplot(x=np.arange("colors"), y=np.arange("rarity"), data=df)

TypeError: unsupported operand type(s) for -: 'str' and 'int'